services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "instance"
        target: /src/instance
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
